remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

collections:
  notes:
    output: true  # 为集合中的文件生成独立页面
    permalink: /:path/:title/  # URL 按文件路径和标题生成

permalink: /:path/:title/

# _config.yml
markdown: kramdown   # 必须使用 kramdown 解析器
highlighter: rouge   # 启用 rouge 语法高亮
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'  # 代码块 CSS 类名
    default_lang: text      # 未指定语言时的默认渲染

head_scripts:
  - /assets/css/custom.css  # 新增自定义样式

# _config.yml
url: "https://rouge3877.github.io"
baseurl: "/"